steps:
- name: node
  id: build tests
  entrypoint: npm
  args:
  - 'install'

- name: node
  id: run test environment tests
  entrypoint: npm
  args:
  - 'run'
  - 'test-test'

# This step runs the integration tests in the Production environment
- name: 'gcr.io/cloud-builders/gcloud'
  id: Trigger Production Environment Integration Tests
  args:
  - 'beta'
  - 'builds'
  - 'triggers'
  - 'run'
  - '4dc8dfef-f5f0-461b-84fe-42eff898e847'
  - '--branch=main'