steps:
#This steps will run the code that we have for our tests 
#to ensure that the code does not break
#If it does breack it will not create a build or an image
- name: node
  id: build tests
  entrypoint: npm
  args:
  - 'install'

- name: node
  id: run development environment tests
  entrypoint: npm
  args:
  - 'run'
  - 'test-dev'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/easyrent-team3:latest'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/easyrent-team3:latest'

# This step runs the integration tests in the Test environment
- name: 'gcr.io/cloud-builders/gcloud'
  id: Trigger Test Environment Integration Tests
  args:
  - 'beta'
  - 'builds'
  - 'triggers'
  - 'run'
  - 'e5a6b460-ba17-4a3d-aaf1-8f4bf21a49a7'
  - '--branch=main'
